import { CREATURES, CREATURE_VARIANTS, createBoss, creatureVariantNote } from '../battle/creatures.js';
import { creatureSvg } from '../battle/creatureArt.js';
import { activeCompanion, creatureAbility, normalizeCreatures } from '../systems/companions.js';
import { escapeHtml } from './dom.js';

export function creatureCollectionMarkup(game, notice = '') {
  const { progress } = game.state;
  const pkg = game.levelPackage;
  const creatures = normalizeCreatures(progress.creatures);
  const companion = activeCompanion(progress, pkg.companions);
  const discovered = CREATURES.filter(creature => creatures.collection[creature.id]);
  const cards = discovered.map(creature => {
    const { level, variant } = creatures.collection[creature.id];
    const definition = pkg.companions[creature.id];
    const ability = creatureAbility(definition, level);
    const next = creatureAbility(definition, level + 1);
    const selected = creatures.partner === creature.id;
    return `<article class="creature-card ${variant} ${selected ? 'is-partner' : ''}" style="--creature-color:${creature.color}"><div class="creature-card-portrait">${creatureSvg(creature.id, '')}${variant !== 'normal' ? `<span class="creature-form-badge">${variant === 'golden' ? '✦ Golden' : '✧ Elite'}</span>` : ''}<span class="creature-level">Lv. ${level}</span></div><div class="creature-card-copy"><h2>${escapeHtml(creature.name)}</h2><p class="creature-personality">${escapeHtml(definition.personality)}</p><h3>${escapeHtml(ability.name)}</h3><p>${escapeHtml(ability.description)}</p><small>Use once per battle, including boss battles. Enhanced attacks require a correct answer.</small>${variant !== 'normal' ? `<p class="creature-partner-perk">${variant === 'golden' ? 'Golden' : 'Elite'} partner: +${CREATURE_VARIANTS[variant].bonusCoins} coins after each battle victory.</p>` : ''}<details><summary>At level ${level + 1}</summary><p>${escapeHtml(next.description)}</p></details><button type="button" class="${selected ? 'secondary' : 'primary'}" data-choose-creature="${creature.id}" aria-pressed="${selected}">${selected ? 'Your partner' : 'Choose as partner'}</button></div></article>`;
  }).join('');
  const bosses = Object.entries(pkg.campaigns || {}).filter(([id]) => (id === pkg.region.id ? progress.story : progress.regions?.[id]?.story)?.bossDefeated).map(([id, campaign]) => {
    const boss = createBoss(pkg.balance, pkg.config.regionLessons[id]);
    return `<article class="creature-boss-record">${creatureSvg(campaign.region.boss, '')}<div><h3>${escapeHtml(campaign.regionStory.bossName)}</h3><p>Lv. ${boss.level} · Defeated</p><small>Story discovery · cannot be a partner</small></div></article>`;
  }).join('');
  return `<div class="panel creatures-panel"><div class="panel-header"><div><p class="panel-kicker">Friends from the fog</p><h1>Creatures</h1></div><button class="secondary" data-close-overlay>Close</button></div><p>Defeat a creature to add it here. We keep its highest defeated level and rarest form; another victory can upgrade either one.</p><details class="creature-variants-guide"><summary>Elite and Golden creatures</summary><p>Some wild creatures appear in special battle forms. Elite appears in about ${Math.round(CREATURE_VARIANTS.elite.chance * 100)}% of encounters; Golden appears in about ${Math.round(CREATURE_VARIANTS.golden.chance * 100)}%.</p><p><b>Elite:</b> ${creatureVariantNote('elite')}</p><p><b>Golden:</b> ${creatureVariantNote('golden')}</p><p>Defeat one to keep its form in your collection. Golden outranks Elite, and neither form is lost if you later defeat a Normal creature. Choose it as your partner to earn its bonus coins after every battle victory, including a boss battle.</p></details><p class="creature-selection-notice" role="status">${escapeHtml(notice)}</p><section class="creature-partner-banner ${companion?.variant || 'normal'}">${companion ? `${creatureSvg(companion.id, '')}<div><span>Your travelling partner</span><h2>${companion.variant === 'normal' ? '' : `${companion.variant === 'golden' ? 'Golden' : 'Elite'} `}${escapeHtml(companion.name)} · Lv. ${companion.level}</h2><b>${escapeHtml(companion.ability.name)}</b><p>${escapeHtml(companion.ability.description)}</p>${companion.bonusCoins ? `<p class="creature-partner-perk">+${companion.bonusCoins} coins after every battle victory.</p>` : ''}</div><button class="secondary" data-release-creature>Travel alone</button>` : '<div><h2>Choose one travelling partner</h2><p>Your partner follows you and has an ability you can use once in each battle. Choose a discovered creature below.</p></div>'}</section><h2 class="creature-discovery-count">${discovered.length} of ${CREATURES.length} creatures discovered</h2>${cards ? `<div class="creature-collection-grid">${cards}</div>` : '<p class="creature-empty">Win a battle on a fog route to add your first creature, then return here to choose it.</p>'}${bosses ? `<section class="creature-bosses"><h2>Boss discoveries</h2><div>${bosses}</div></section>` : ''}</div>`;
}
